// Generated by gencs from ontology_msgs/Activity.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {
  namespace ontology_msgs {

    [System.Serializable]
    public class Activity : ROSMessage
    {
      public string name;
      public string className;
      public System.Collections.Generic.List<string>  inHand;
      public System.Collections.Generic.List<string>  actedOn;


      public Activity()
      {
        name = "";
        className = "";
        inHand = new System.Collections.Generic.List<string>();
        actedOn = new System.Collections.Generic.List<string>();

      }

      public Activity(string _name, string _className, System.Collections.Generic.List<string>  _inHand, System.Collections.Generic.List<string>  _actedOn)
      {
        name = _name;
        className = _className;
        inHand = _inHand;
        actedOn = _actedOn;
      }

      new public static string GetMessageType()
      {
        return "ontology_msgs/Activity";
      }

      new public static string GetMD5Hash()
      {
        return "b82e86ad6fb4d8e3122b3a52e675e973";
      }

    } // class Activity

  } // namespace ontology_msgs

} // namespace ROSBridgeLib
