// Generated by gencs from ontology_msgs/DisplayLabel.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {
  namespace ontology_msgs {

    [System.Serializable]
    public class DisplayLabel : ROSMessage
    {
      public string text;
      public System.UInt32 lbl_id;


      public DisplayLabel()
      {
        text = "";
        lbl_id = 0;

      }

      public DisplayLabel(string _text, System.UInt32 _lbl_id)
      {
        text = _text;
        lbl_id = _lbl_id;
      }

      new public static string GetMessageType()
      {
        return "ontology_msgs/DisplayLabel";
      }

      new public static string GetMD5Hash()
      {
        return "9c40d93b6e19d3165743dc6281bd45ce";
      }

    } // class DisplayLabel

  } // namespace ontology_msgs

} // namespace ROSBridgeLib
