// Generated by gencs from ontology_msgs/GraphUpdate.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.ontology_msgs;

namespace ROSBridgeLib {
  namespace ontology_msgs {

    [System.Serializable]
    public class GraphUpdate : ROSMessage
    {
      public System.Int32 operation;
      public ontology_msgs.GraphNode node;

      public const System.Int32 ADD = 1;
      public const System.Int32 REMOVE = 2;
      public const System.Int32 CHANGE = 3;

      public GraphUpdate()
      {
        operation = 0;
        node = new ontology_msgs.GraphNode();

      }

      public GraphUpdate(System.Int32 _operation, ontology_msgs.GraphNode _node)
      {
        operation = _operation;
        node = _node;
      }

      new public static string GetMessageType()
      {
        return "ontology_msgs/GraphUpdate";
      }

      new public static string GetMD5Hash()
      {
        return "929813e532932a473065164384617aca";
      }

    } // class GraphUpdate

  } // namespace ontology_msgs

} // namespace ROSBridgeLib
