// Generated by gencs from ontology_msgs/Graph.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.ontology_msgs;

namespace ROSBridgeLib {
  namespace ontology_msgs {

    [System.Serializable]
    public class Graph : ROSMessage
    {
      public System.Collections.Generic.List<ontology_msgs.GraphNode>  nodes;


      public Graph()
      {
        nodes = new System.Collections.Generic.List<ontology_msgs.GraphNode>();

      }

      public Graph(System.Collections.Generic.List<ontology_msgs.GraphNode>  _nodes)
      {
        nodes = _nodes;
      }

      new public static string GetMessageType()
      {
        return "ontology_msgs/Graph";
      }

      new public static string GetMD5Hash()
      {
        return "56196e1214e6ba3f93ccfe300858c265";
      }

    } // class Graph

  } // namespace ontology_msgs

} // namespace ROSBridgeLib
