// Generated by gencs from ontology_msgs/GraphNode.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {
  namespace ontology_msgs {

    [System.Serializable]
    public class GraphNode : ROSMessage
    {
      public string name;
      public System.Collections.Generic.List<string>  neighbors;
      public System.Collections.Generic.List<float>  weights;


      public GraphNode()
      {
        name = "";
        neighbors = new System.Collections.Generic.List<string>();
        weights = new System.Collections.Generic.List<float>();

      }

      public GraphNode(string _name, System.Collections.Generic.List<string>  _neighbors, System.Collections.Generic.List<float>  _weights)
      {
        name = _name;
        neighbors = _neighbors;
        weights = _weights;
      }

      new public static string GetMessageType()
      {
        return "ontology_msgs/GraphNode";
      }

      new public static string GetMD5Hash()
      {
        return "c777df17fa82fc2bc219d31950f8a3f2";
      }

    } // class GraphNode

  } // namespace ontology_msgs

} // namespace ROSBridgeLib
