// Generated by gencs from ontology_msgs/HandUpdate.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.ontology_msgs;

namespace ROSBridgeLib {
  namespace ontology_msgs {

    [System.Serializable]
    public class HandUpdate : ROSMessage
    {
      public ontology_msgs.ObjUpdate handState;
      public float grasp;
      public float use;
      public string obj_inHand;


      public HandUpdate()
      {
        handState = new ontology_msgs.ObjUpdate();
        grasp = 0.0f;
        use = 0.0f;
        obj_inHand = "";

      }

      public HandUpdate(ontology_msgs.ObjUpdate _handState, float _grasp, float _use, string _obj_inHand)
      {
        handState = _handState;
        grasp = _grasp;
        use = _use;
        obj_inHand = _obj_inHand;
      }

      new public static string GetMessageType()
      {
        return "ontology_msgs/HandUpdate";
      }

      new public static string GetMD5Hash()
      {
        return "95deb49a332700fbcc09a2b4e933cfad";
      }

    } // class HandUpdate

  } // namespace ontology_msgs

} // namespace ROSBridgeLib
