// Generated by gencs from ontology_msgs/ObjUpdate.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.geometry_msgs;

namespace ROSBridgeLib {
  namespace ontology_msgs {

    [System.Serializable]
    public class ObjUpdate : ROSMessage
    {
      public ROSBridgeLib.msg_helpers.Time timestamp;
      public string name;
      public UnityEngine.Vector3 position;
      public UnityEngine.Quaternion orientation;
      public UnityEngine.Vector3 velocity;


      public ObjUpdate()
      {
        timestamp = new ROSBridgeLib.msg_helpers.Time();
        name = "";
        position = new UnityEngine.Vector3();
        orientation = new UnityEngine.Quaternion();
        velocity = new UnityEngine.Vector3();

      }

      public ObjUpdate(ROSBridgeLib.msg_helpers.Time _timestamp, string _name, UnityEngine.Vector3 _position, UnityEngine.Quaternion _orientation, UnityEngine.Vector3 _velocity)
      {
        timestamp = _timestamp;
        name = _name;
        position = _position;
        orientation = _orientation;
        velocity = _velocity;
      }

      new public static string GetMessageType()
      {
        return "ontology_msgs/ObjUpdate";
      }

      new public static string GetMD5Hash()
      {
        return "072c850c19848e49893d8e7ac8c420ce";
      }

    } // class ObjUpdate

  } // namespace ontology_msgs

} // namespace ROSBridgeLib
