// Generated by gencs from ontology_msgs/OntoPropertyList.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.ontology_msgs;

namespace ROSBridgeLib {
  namespace ontology_msgs {

    [System.Serializable]
    public class OntoPropertyList : ROSMessage
    {
      public System.Collections.Generic.List<ontology_msgs.OntoProperty>  properties;


      public OntoPropertyList()
      {
        properties = new System.Collections.Generic.List<ontology_msgs.OntoProperty>();

      }

      public OntoPropertyList(System.Collections.Generic.List<ontology_msgs.OntoProperty>  _properties)
      {
        properties = _properties;
      }

      new public static string GetMessageType()
      {
        return "ontology_msgs/OntoPropertyList";
      }

      new public static string GetMD5Hash()
      {
        return "d0c69cfc78d8e7127456a60156772e70";
      }

    } // class OntoPropertyList

  } // namespace ontology_msgs

} // namespace ROSBridgeLib
