// Generated by gencs from ontology_msgs/SimulationStateChange.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {
  namespace ontology_msgs {

    [System.Serializable]
    public class SimulationStateChange : ROSMessage
    {
      public System.UInt32 new_state;
      public ROSBridgeLib.msg_helpers.Time timestamp;

      public const System.UInt32 SIMULATION_LOADED = 1;
      public const System.UInt32 SIMULATION_STARTED = 2;
      public const System.UInt32 SIMULATION_STOPPED = 4;

      public SimulationStateChange()
      {
        new_state = 0;
        timestamp = new ROSBridgeLib.msg_helpers.Time();

      }

      public SimulationStateChange(System.UInt32 _new_state, ROSBridgeLib.msg_helpers.Time _timestamp)
      {
        new_state = _new_state;
        timestamp = _timestamp;
      }

      new public static string GetMessageType()
      {
        return "ontology_msgs/SimulationStateChange";
      }

      new public static string GetMD5Hash()
      {
        return "b3355582f4e8affb5130404d0dc32891";
      }

    } // class SimulationStateChange

  } // namespace ontology_msgs

} // namespace ROSBridgeLib
