// Generated by gencs from file ontology_svcs/DisplayLabel.srv
// DO NOT EDIT THIS FILE BY HAND


using ROSBridgeLib.ontology_svcs;

namespace ROSBridgeLib {
  namespace ontology_svcs {

    public class DisplayLabel : ROSBridgeServiceProvider<ontology_svcs.DisplayLabelRequest>
    {
      public DisplayLabel(string serviceName) : base(serviceName)
      {
        _type = "ontology_svcs/DisplayLabel";
      }

      public DisplayLabel(string serviceName, string serviceType = "ontology_svcs/DisplayLabel") : base(serviceName, serviceType) {}
    }

  } // namespace ontology_svcs
} // namespace ROSBridgeLib

