// Generated by gencs from ontology_svcs/GetActivities.srv
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {
  namespace ontology_svcs {

    [System.Serializable]
    public class GetActivitiesRequest : ServiceArgs
    {


      public GetActivitiesRequest()
      {

      }


      new public static string GetMessageType()
      {
        return "ontology_svcs/GetActivitiesRequest";
      }

      new public static string GetMD5Hash()
      {
        return "d41d8cd98f00b204e9800998ecf8427e";
      }

    } // class GetActivitiesRequest

  } // namespace ontology_svcs

} // namespace ROSBridgeLib
