// Generated by gencs from file ontology_svcs/GetActivityGraph.srv
// DO NOT EDIT THIS FILE BY HAND


using ROSBridgeLib.ontology_svcs;

namespace ROSBridgeLib {
  namespace ontology_svcs {

    public class GetActivityGraph : ROSBridgeServiceProvider<ontology_svcs.GetActivityGraphRequest>
    {
      public GetActivityGraph(string serviceName) : base(serviceName)
      {
        _type = "ontology_svcs/GetActivityGraph";
      }

      public GetActivityGraph(string serviceName, string serviceType = "ontology_svcs/GetActivityGraph") : base(serviceName, serviceType) {}
    }

  } // namespace ontology_svcs
} // namespace ROSBridgeLib

