// Generated by gencs from file ontology_svcs/GetActivities.srv
// DO NOT EDIT THIS FILE BY HAND


using ROSBridgeLib.ontology_svcs;

namespace ROSBridgeLib {
  namespace ontology_svcs {

    public class GetActivities : ROSBridgeServiceProvider<ontology_svcs.GetActivitiesRequest>
    {
      public GetActivities(string serviceName) : base(serviceName)
      {
        _type = "ontology_svcs/GetActivities";
      }

      public GetActivities(string serviceName, string serviceType = "ontology_svcs/GetActivities") : base(serviceName, serviceType) {}
    }

  } // namespace ontology_svcs
} // namespace ROSBridgeLib

