// Generated by gencs from file ontology_svcs/GetActivity.srv
// DO NOT EDIT THIS FILE BY HAND


using ROSBridgeLib.ontology_svcs;

namespace ROSBridgeLib {
  namespace ontology_svcs {

    public class GetActivity : ROSBridgeServiceProvider<ontology_svcs.GetActivityRequest>
    {
      public GetActivity(string serviceName) : base(serviceName)
      {
        _type = "ontology_svcs/GetActivity";
      }

      public GetActivity(string serviceName, string serviceType = "ontology_svcs/GetActivity") : base(serviceName, serviceType) {}
    }

  } // namespace ontology_svcs
} // namespace ROSBridgeLib

