// Generated by gencs from ontology_svcs/GetActivityGraph.srv
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {
  namespace ontology_svcs {

    [System.Serializable]
    public class GetActivityGraphRequest : ServiceArgs
    {
      public string name;


      public GetActivityGraphRequest()
      {
        name = "";

      }

      public GetActivityGraphRequest(string _name)
      {
        name = _name;
      }

      new public static string GetMessageType()
      {
        return "ontology_svcs/GetActivityGraphRequest";
      }

      new public static string GetMD5Hash()
      {
        return "c1f3d28f1b044c871e6eff2e9fc3c667";
      }

    } // class GetActivityGraphRequest

  } // namespace ontology_svcs

} // namespace ROSBridgeLib
