// Generated by gencs from file ontology_svcs/GetAllClassInstancesWithPoses.srv
// DO NOT EDIT THIS FILE BY HAND


using ROSBridgeLib.ontology_svcs;

namespace ROSBridgeLib {
  namespace ontology_svcs {

    public class GetAllClassInstancesWithPoses : ROSBridgeServiceProvider<ontology_svcs.GetAllClassInstancesWithPosesRequest>
    {
      public GetAllClassInstancesWithPoses(string serviceName) : base(serviceName)
      {
        _type = "ontology_svcs/GetAllClassInstancesWithPoses";
      }

      public GetAllClassInstancesWithPoses(string serviceName, string serviceType = "ontology_svcs/GetAllClassInstancesWithPoses") : base(serviceName, serviceType) {}
    }

  } // namespace ontology_svcs
} // namespace ROSBridgeLib

