// Generated by gencs from file ontology_svcs/GetAllClassInstances.srv
// DO NOT EDIT THIS FILE BY HAND


using ROSBridgeLib.ontology_svcs;

namespace ROSBridgeLib {
  namespace ontology_svcs {

    public class GetAllClassInstances : ROSBridgeServiceProvider<ontology_svcs.GetAllClassInstancesRequest>
    {
      public GetAllClassInstances(string serviceName) : base(serviceName)
      {
        _type = "ontology_svcs/GetAllClassInstances";
      }

      public GetAllClassInstances(string serviceName, string serviceType = "ontology_svcs/GetAllClassInstances") : base(serviceName, serviceType) {}
    }

  } // namespace ontology_svcs
} // namespace ROSBridgeLib

