// Generated by gencs from ontology_svcs/GetAllClassInstances.srv
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.ontology_msgs;

namespace ROSBridgeLib {
  namespace ontology_svcs {

    [System.Serializable]
    public class GetAllClassInstancesResponse : ServiceResponse
    {
      public System.Collections.Generic.List<string>  classes;
      public System.Collections.Generic.List<string>  entityNames;
      public System.Collections.Generic.List<ontology_msgs.OntoPropertyList>  properties;


      public GetAllClassInstancesResponse()
      {
        classes = new System.Collections.Generic.List<string>();
        entityNames = new System.Collections.Generic.List<string>();
        properties = new System.Collections.Generic.List<ontology_msgs.OntoPropertyList>();

      }

      public GetAllClassInstancesResponse(System.Collections.Generic.List<string>  _classes, System.Collections.Generic.List<string>  _entityNames, System.Collections.Generic.List<ontology_msgs.OntoPropertyList>  _properties)
      {
        classes = _classes;
        entityNames = _entityNames;
        properties = _properties;
      }

      new public static string GetMessageType()
      {
        return "ontology_svcs/GetAllClassInstancesResponse";
      }

      new public static string GetMD5Hash()
      {
        return "41ebf82872f0ddcf5275793d1a6d1386";
      }

    } // class GetAllClassInstancesResponse

  } // namespace ontology_svcs

} // namespace ROSBridgeLib
