// Generated by gencs from ontology_svcs/GetActivities.srv
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.ontology_msgs;

namespace ROSBridgeLib {
  namespace ontology_svcs {

    [System.Serializable]
    public class GetActivitiesResponse : ServiceResponse
    {
      public System.Collections.Generic.List<ontology_msgs.Activity>  activities;


      public GetActivitiesResponse()
      {
        activities = new System.Collections.Generic.List<ontology_msgs.Activity>();

      }

      public GetActivitiesResponse(System.Collections.Generic.List<ontology_msgs.Activity>  _activities)
      {
        activities = _activities;
      }

      new public static string GetMessageType()
      {
        return "ontology_svcs/GetActivitiesResponse";
      }

      new public static string GetMD5Hash()
      {
        return "ff2bf8fab6830a9b5a1516614c40d67a";
      }

    } // class GetActivitiesResponse

  } // namespace ontology_svcs

} // namespace ROSBridgeLib
