// Generated by gencs from ontology_svcs/RelabelActivity.srv
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {
  namespace ontology_svcs {

    [System.Serializable]
    public class RelabelActivityRequest : ServiceArgs
    {
      public string oldName;
      public string newName;


      public RelabelActivityRequest()
      {
        oldName = "";
        newName = "";

      }

      public RelabelActivityRequest(string _oldName, string _newName)
      {
        oldName = _oldName;
        newName = _newName;
      }

      new public static string GetMessageType()
      {
        return "ontology_svcs/RelabelActivityRequest";
      }

      new public static string GetMD5Hash()
      {
        return "8b5a93be4eedc187b5348927d8d571d5";
      }

    } // class RelabelActivityRequest

  } // namespace ontology_svcs

} // namespace ROSBridgeLib
