// Generated by gencs from file ontology_svcs/RelabelObject.srv
// DO NOT EDIT THIS FILE BY HAND


using ROSBridgeLib.ontology_svcs;

namespace ROSBridgeLib {
  namespace ontology_svcs {

    public class RelabelObject : ROSBridgeServiceProvider<ontology_svcs.RelabelObjectRequest>
    {
      public RelabelObject(string serviceName) : base(serviceName)
      {
        _type = "ontology_svcs/RelabelObject";
      }

      public RelabelObject(string serviceName, string serviceType = "ontology_svcs/RelabelObject") : base(serviceName, serviceType) {}
    }

  } // namespace ontology_svcs
} // namespace ROSBridgeLib

