// Generated by gencs from file ontology_svcs/RelabelActivity.srv
// DO NOT EDIT THIS FILE BY HAND


using ROSBridgeLib.ontology_svcs;

namespace ROSBridgeLib {
  namespace ontology_svcs {

    public class RelabelActivity : ROSBridgeServiceProvider<ontology_svcs.RelabelActivityRequest>
    {
      public RelabelActivity(string serviceName) : base(serviceName)
      {
        _type = "ontology_svcs/RelabelActivity";
      }

      public RelabelActivity(string serviceName, string serviceType = "ontology_svcs/RelabelActivity") : base(serviceName, serviceType) {}
    }

  } // namespace ontology_svcs
} // namespace ROSBridgeLib

