// Generated by gencs from ontology_svcs/RelabelObject.srv
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {
  namespace ontology_svcs {

    [System.Serializable]
    public class RelabelObjectRequest : ServiceArgs
    {
      public string objName;
      public string objClass;


      public RelabelObjectRequest()
      {
        objName = "";
        objClass = "";

      }

      public RelabelObjectRequest(string _objName, string _objClass)
      {
        objName = _objName;
        objClass = _objClass;
      }

      new public static string GetMessageType()
      {
        return "ontology_svcs/RelabelObjectRequest";
      }

      new public static string GetMD5Hash()
      {
        return "418ca04d9197b9efff8a84f49ba83ddd";
      }

    } // class RelabelObjectRequest

  } // namespace ontology_svcs

} // namespace ROSBridgeLib
