// Generated by gencs from ontology_svcs/RelabelObject.srv
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {
  namespace ontology_svcs {

    [System.Serializable]
    public class RelabelObjectResponse : ServiceResponse
    {
      public string newInstanceName;
      public bool success;


      public RelabelObjectResponse()
      {
        newInstanceName = "";
        success = false;

      }

      public RelabelObjectResponse(string _newInstanceName, bool _success)
      {
        newInstanceName = _newInstanceName;
        success = _success;
      }

      new public static string GetMessageType()
      {
        return "ontology_svcs/RelabelObjectResponse";
      }

      new public static string GetMD5Hash()
      {
        return "2c51df3313f868a6de8d6bf1b4970ed0";
      }

    } // class RelabelObjectResponse

  } // namespace ontology_svcs

} // namespace ROSBridgeLib
