// Generated by gencs from geometry_msgs/Point32.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {
  namespace geometry_msgs {

    [System.Serializable]
    public class Point32 : ROSMessage
    {
      public float x;
      public float y;
      public float z;


      public Point32()
      {
        x = 0.0f;
        y = 0.0f;
        z = 0.0f;

      }

      public Point32(float _x, float _y, float _z)
      {
        x = _x;
        y = _y;
        z = _z;
      }

      new public static string GetMessageType()
      {
        return "geometry_msgs/Point32";
      }

      new public static string GetMD5Hash()
      {
        return "cc153912f1453b708d221682bc23d9ac";
      }

    } // class Point32

  } // namespace geometry_msgs

} // namespace ROSBridgeLib
