// Generated by gencs from geometry_msgs/PoseWithCovarianceStamped.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.std_msgs;
using ROSBridgeLib.geometry_msgs;

namespace ROSBridgeLib {
  namespace geometry_msgs {

    [System.Serializable]
    public class PoseWithCovarianceStamped : ROSMessage
    {
      public std_msgs.Header header;
      public geometry_msgs.PoseWithCovariance pose;


      public PoseWithCovarianceStamped()
      {
        header = new std_msgs.Header();
        pose = new geometry_msgs.PoseWithCovariance();

      }

      public PoseWithCovarianceStamped(std_msgs.Header _header, geometry_msgs.PoseWithCovariance _pose)
      {
        header = _header;
        pose = _pose;
      }

      new public static string GetMessageType()
      {
        return "geometry_msgs/PoseWithCovarianceStamped";
      }

      new public static string GetMD5Hash()
      {
        return "953b798c0f514ff060a53a3498ce6246";
      }

    } // class PoseWithCovarianceStamped

  } // namespace geometry_msgs

} // namespace ROSBridgeLib
