// Generated by gencs from turtlesim/Color.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {
  namespace turtlesim {

    [System.Serializable]
    public class Color : ROSMessage
    {
      public byte r;
      public byte g;
      public byte b;


      public Color()
      {
        r = 0;
        g = 0;
        b = 0;

      }

      public Color(byte _r, byte _g, byte _b)
      {
        r = _r;
        g = _g;
        b = _b;
      }

      new public static string GetMessageType()
      {
        return "turtlesim/Color";
      }

      new public static string GetMD5Hash()
      {
        return "353891e354491c51aabe32df673fb446";
      }

    } // class Color

  } // namespace turtlesim

} // namespace ROSBridgeLib
