// Generated by gencs from turtlesim/Pose.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {
  namespace turtlesim {

    [System.Serializable]
    public class Pose : ROSMessage
    {
      public float x;
      public float y;
      public float theta;
      public float linear_velocity;
      public float angular_velocity;


      public Pose()
      {
        x = 0.0f;
        y = 0.0f;
        theta = 0.0f;
        linear_velocity = 0.0f;
        angular_velocity = 0.0f;

      }

      public Pose(float _x, float _y, float _theta, float _linear_velocity, float _angular_velocity)
      {
        x = _x;
        y = _y;
        theta = _theta;
        linear_velocity = _linear_velocity;
        angular_velocity = _angular_velocity;
      }

      new public static string GetMessageType()
      {
        return "turtlesim/Pose";
      }

      new public static string GetMD5Hash()
      {
        return "863b248d5016ca62ea2e895ae5265cf9";
      }

    } // class Pose

  } // namespace turtlesim

} // namespace ROSBridgeLib
