// Generated by gencs from file turtlesim/SetPen.srv
// DO NOT EDIT THIS FILE BY HAND


using ROSBridgeLib.turtlesim;

namespace ROSBridgeLib {
  namespace turtlesim {

    public class SetPen : ROSBridgeServiceProvider<turtlesim.SetPenRequest>
    {
      public SetPen(string serviceName) : base(serviceName)
      {
        _type = "turtlesim/SetPen";
      }

      public SetPen(string serviceName, string serviceType = "turtlesim/SetPen") : base(serviceName, serviceType) {}
    }

  } // namespace turtlesim
} // namespace ROSBridgeLib

