// Generated by gencs from turtlesim/SetPen.srv
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {
  namespace turtlesim {

    [System.Serializable]
    public class SetPenRequest : ServiceArgs
    {
      public byte r;
      public byte g;
      public byte b;
      public byte width;
      public byte off;


      public SetPenRequest()
      {
        r = 0;
        g = 0;
        b = 0;
        width = 0;
        off = 0;

      }

      public SetPenRequest(byte _r, byte _g, byte _b, byte _width, byte _off)
      {
        r = _r;
        g = _g;
        b = _b;
        width = _width;
        off = _off;
      }

      new public static string GetMessageType()
      {
        return "turtlesim/SetPenRequest";
      }

      new public static string GetMD5Hash()
      {
        return "9f452acce566bf0c0954594f69a8e41b";
      }

    } // class SetPenRequest

  } // namespace turtlesim

} // namespace ROSBridgeLib
