// Generated by gencs from turtlesim/Spawn.srv
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {
  namespace turtlesim {

    [System.Serializable]
    public class SpawnRequest : ServiceArgs
    {
      public float x;
      public float y;
      public float theta;
      public string name;


      public SpawnRequest()
      {
        x = 0.0f;
        y = 0.0f;
        theta = 0.0f;
        name = "";

      }

      public SpawnRequest(float _x, float _y, float _theta, string _name)
      {
        x = _x;
        y = _y;
        theta = _theta;
        name = _name;
      }

      new public static string GetMessageType()
      {
        return "turtlesim/SpawnRequest";
      }

      new public static string GetMD5Hash()
      {
        return "57f001c49ab7b11d699f8606c1f4f7ff";
      }

    } // class SpawnRequest

  } // namespace turtlesim

} // namespace ROSBridgeLib
