// Generated by gencs from turtlesim/TeleportAbsolute.srv
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {
  namespace turtlesim {

    [System.Serializable]
    public class TeleportAbsoluteRequest : ServiceArgs
    {
      public float x;
      public float y;
      public float theta;


      public TeleportAbsoluteRequest()
      {
        x = 0.0f;
        y = 0.0f;
        theta = 0.0f;

      }

      public TeleportAbsoluteRequest(float _x, float _y, float _theta)
      {
        x = _x;
        y = _y;
        theta = _theta;
      }

      new public static string GetMessageType()
      {
        return "turtlesim/TeleportAbsoluteRequest";
      }

      new public static string GetMD5Hash()
      {
        return "a130bc60ee6513855dc62ea83fcc5b20";
      }

    } // class TeleportAbsoluteRequest

  } // namespace turtlesim

} // namespace ROSBridgeLib
