// Generated by gencs from turtlesim/TeleportAbsolute.srv
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {
  namespace turtlesim {

    [System.Serializable]
    public class TeleportAbsoluteResponse : ServiceResponse
    {


      public TeleportAbsoluteResponse()
      {

      }


      new public static string GetMessageType()
      {
        return "turtlesim/TeleportAbsoluteResponse";
      }

      new public static string GetMD5Hash()
      {
        return "d41d8cd98f00b204e9800998ecf8427e";
      }

    } // class TeleportAbsoluteResponse

  } // namespace turtlesim

} // namespace ROSBridgeLib
