// Generated by gencs from file turtlesim/TeleportRelative.srv
// DO NOT EDIT THIS FILE BY HAND


using ROSBridgeLib.turtlesim;

namespace ROSBridgeLib {
  namespace turtlesim {

    public class TeleportRelative : ROSBridgeServiceProvider<turtlesim.TeleportRelativeRequest>
    {
      public TeleportRelative(string serviceName) : base(serviceName)
      {
        _type = "turtlesim/TeleportRelative";
      }

      public TeleportRelative(string serviceName, string serviceType = "turtlesim/TeleportRelative") : base(serviceName, serviceType) {}
    }

  } // namespace turtlesim
} // namespace ROSBridgeLib

