// Generated by gencs from turtlesim/TeleportRelative.srv
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {
  namespace turtlesim {

    [System.Serializable]
    public class TeleportRelativeRequest : ServiceArgs
    {
      public float linear;
      public float angular;


      public TeleportRelativeRequest()
      {
        linear = 0.0f;
        angular = 0.0f;

      }

      public TeleportRelativeRequest(float _linear, float _angular)
      {
        linear = _linear;
        angular = _angular;
      }

      new public static string GetMessageType()
      {
        return "turtlesim/TeleportRelativeRequest";
      }

      new public static string GetMD5Hash()
      {
        return "9d5c2dcd348ac8f76ce2a4307bd63a13";
      }

    } // class TeleportRelativeRequest

  } // namespace turtlesim

} // namespace ROSBridgeLib
