// Generated by gencs from file turtlesim/TeleportAbsolute.srv
// DO NOT EDIT THIS FILE BY HAND


using ROSBridgeLib.turtlesim;

namespace ROSBridgeLib {
  namespace turtlesim {

    public class TeleportAbsolute : ROSBridgeServiceProvider<turtlesim.TeleportAbsoluteRequest>
    {
      public TeleportAbsolute(string serviceName) : base(serviceName)
      {
        _type = "turtlesim/TeleportAbsolute";
      }

      public TeleportAbsolute(string serviceName, string serviceType = "turtlesim/TeleportAbsolute") : base(serviceName, serviceType) {}
    }

  } // namespace turtlesim
} // namespace ROSBridgeLib

