// Generated by gencs from file simple_unity_bot/DisplayLabel.srv
// DO NOT EDIT THIS FILE BY HAND


using ROSBridgeLib.simple_unity_bot;

namespace ROSBridgeLib {
  namespace simple_unity_bot {

    public class DisplayLabel : ROSBridgeServiceProvider<simple_unity_bot.DisplayLabelRequest>
    {
      public DisplayLabel(string serviceName) : base(serviceName)
      {
        _type = "simple_unity_bot/DisplayLabel";
      }

      public DisplayLabel(string serviceName, string serviceType = "simple_unity_bot/DisplayLabel") : base(serviceName, serviceType) {}
    }

  } // namespace simple_unity_bot
} // namespace ROSBridgeLib

