// Generated by gencs from simple_unity_bot/HandState.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;


namespace ROSBridgeLib {
  namespace simple_unity_bot {

    [System.Serializable]
    public class HandState : ROSMessage
    {
      public string name;
      public float grasp;
      public float use;


      public HandState()
      {
        name = "";
        grasp = 0.0f;
        use = 0.0f;

      }

      public HandState(string _name, float _grasp, float _use)
      {
        name = _name;
        grasp = _grasp;
        use = _use;
      }

      new public static string GetMessageType()
      {
        return "simple_unity_bot/HandState";
      }

      new public static string GetMD5Hash()
      {
        return "c9dbca2feedbe0f3b2ae4e7c380d3e4d";
      }

    } // class HandState

  } // namespace simple_unity_bot

} // namespace ROSBridgeLib
