// Generated by gencs from simple_unity_bot/SimplePoseArray.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using ROSBridgeLib;
using UnityEngine;

using ROSBridgeLib.std_msgs;
using ROSBridgeLib.simple_unity_bot;

namespace ROSBridgeLib {
  namespace simple_unity_bot {

    [System.Serializable]
    public class SimplePoseArray : ROSMessage
    {
      public std_msgs.Header header;
      public System.Collections.Generic.List<simple_unity_bot.SimplePose>  poses;


      public SimplePoseArray()
      {
        header = new std_msgs.Header();
        poses = new System.Collections.Generic.List<simple_unity_bot.SimplePose>();

      }

      public SimplePoseArray(std_msgs.Header _header, System.Collections.Generic.List<simple_unity_bot.SimplePose>  _poses)
      {
        header = _header;
        poses = _poses;
      }

      new public static string GetMessageType()
      {
        return "simple_unity_bot/SimplePoseArray";
      }

      new public static string GetMD5Hash()
      {
        return "3b94a52ad931205a864703d07540c506";
      }

    } // class SimplePoseArray

  } // namespace simple_unity_bot

} // namespace ROSBridgeLib
